import Foundation

/// Deterministic, offline classification of filesystem entries into
/// `ReclaimCategory` values. Ordered rules — the first match wins.
///
/// Rules are intentionally conservative: anything not recognized as a cache /
/// build artifact / dependency store stays `keep`. The LLM assistant handles the
/// long tail; this layer is the grounded, no-network default.
enum ReclaimRules {

    /// A rule matches on the entry's own name and/or its full path.
    private struct Rule {
        let matches: (_ name: String, _ path: String, _ isDir: Bool) -> Bool
        let category: ReclaimCategory
    }

    private static let home = FileManager.default.homeDirectoryForCurrentUser.path

    /// Match an exact directory basename (case-sensitive as on disk).
    private static func name(_ n: String, _ category: ReclaimCategory) -> Rule {
        Rule(matches: { name, _, isDir in isDir && name == n }, category: category)
    }
    /// Match any entry whose path contains a substring.
    private static func pathContains(_ frag: String, _ category: ReclaimCategory) -> Rule {
        Rule(matches: { _, path, _ in path.contains(frag) }, category: category)
    }
    /// Match an entry directly inside a directory (path prefix).
    private static func under(_ prefix: String, _ category: ReclaimCategory) -> Rule {
        let full = prefix.hasPrefix("~") ? home + String(prefix.dropFirst()) : prefix
        return Rule(matches: { _, path, _ in path == full || path.hasPrefix(full + "/") }, category: category)
    }
    private static func ext(_ e: String, _ category: ReclaimCategory) -> Rule {
        Rule(matches: { name, _, isDir in !isDir && name.lowercased().hasSuffix("." + e) }, category: category)
    }

    // Categories
    private static let npm      = ReclaimCategory(name: "npm packages", reclaim: .safe, reason: "Reinstall with `npm install`", reproducible: true)
    private static let derived  = ReclaimCategory(name: "Xcode DerivedData", reclaim: .safe, reason: "Rebuilt by Xcode", reproducible: true)
    private static let cache    = ReclaimCategory(name: "App cache", reclaim: .safe, reason: "Apps regenerate caches", reproducible: true)
    private static let buildOut = ReclaimCategory(name: "Build output", reclaim: .safe, reason: "Recreated on next build", reproducible: true)
    private static let pkgStore = ReclaimCategory(name: "Package store", reclaim: .safe, reason: "Re-downloaded on demand", reproducible: true)
    private static let pyCache  = ReclaimCategory(name: "Python cache", reclaim: .safe, reason: "Regenerated by Python", reproducible: true)
    private static let venv     = ReclaimCategory(name: "Virtualenv", reclaim: .safe, reason: "Recreate from requirements", reproducible: true)
    private static let simulator = ReclaimCategory(name: "Simulator data", reclaim: .safe, reason: "Xcode simulators", reproducible: true)
    private static let trash    = ReclaimCategory(name: "Trash", reclaim: .safe, reason: "Already discarded", reproducible: false)
    private static let logs     = ReclaimCategory(name: "Logs", reclaim: .caution, reason: "Diagnostic logs", reproducible: false)
    private static let docker   = ReclaimCategory(name: "Docker data", reclaim: .caution, reason: "Images/volumes — verify first", reproducible: true)
    private static let container = ReclaimCategory(name: "App container", reclaim: .caution, reason: "May hold app data", reproducible: false)
    private static let appBundle = ReclaimCategory(name: "Application", reclaim: .keep, reason: "Installed app", reproducible: false)
    private static let photos   = ReclaimCategory(name: "Photos library", reclaim: .keep, reason: "Your photos", reproducible: false)
    private static let userDocs  = ReclaimCategory(name: "User documents", reclaim: .keep, reason: "Personal files", reproducible: false)

    private static let rules: [Rule] = [
        // Keep first: never let a broad cache rule swallow these.
        under("~/Documents", userDocs),
        under("~/Desktop", userDocs),
        under("~/Pictures", photos),
        name("node_modules", npm),
        name("DerivedData", derived),
        pathContains("/Library/Developer/Xcode/DerivedData", derived),
        pathContains("/Library/Developer/CoreSimulator", simulator),
        name("__pycache__", pyCache),
        name(".venv", venv),
        name("venv", venv),
        name("Pods", pkgStore),
        name("Carthage", pkgStore),
        name(".gradle", pkgStore),
        name(".m2", pkgStore),
        name(".cargo", pkgStore),
        name(".next", buildOut),
        name(".turbo", buildOut),
        name("dist", buildOut),
        name("build", buildOut),
        name("target", buildOut),
        name(".Trash", trash),
        pathContains("com.docker", docker),
        ext("app", appBundle),
        ext("photoslibrary", photos),
        ext("log", logs),
        // Broad, lower-priority buckets last.
        under("~/Library/Caches", cache),
        under("~/Library/Containers", container),
    ]

    /// Classify an entry. Returns nil when nothing matches (treated as unknown/keep).
    static func classify(url: URL, isDirectory: Bool) -> ReclaimCategory? {
        let name = url.lastPathComponent
        let path = url.path
        for rule in rules where rule.matches(name, path, isDirectory) {
            return rule.category
        }
        return nil
    }
}
